### ISSUE TITLE
Request to include Beaumont

### ISSUE THREAD

**Issue by ajmc199** [gallo-json/air-pollution-forecast#1]
Hello,
I don't know much about coding etc. so please bear with me. I created a github account in order to find the creator of this and to make a feature request.I like this website because it is simple, I was using it a while back but now I can't find the link. Can you please paste it ?

I transit near Beaumont tx close to a superfund site. I'm sure you know how polluted that area is ("The golden triangle"),  this tool is useful to me for air pollution. However I noticed from the description the forecast doesn't extend as far east to Jefferson county. Only Harris, Galveston and Brazoria. Is there any way you can include forecast in Jefferson county ? I would appreciate it very much.

Thank you

**Comment by gallo-json** [comment]
Hello ajmc199,

Thank you for your feature request. I appreciate the effort you put into contacting me, that is my fault. I should have made the website accept feature requests instead of going the great lengths like you did.

Unfortunately, I've taken down the website because I've gotten busy with school and can't continue maintaining it. The website I used as inspiration while making this project is https://aqicn.org/map/northamerica/, you can probably get by with that for your needs. But it only has 3 stations in Beaumont, TX.

Again, thank your for your time and for using my tool. I truly appreciate it.

Thank you for your understanding,

Jose S. Gallo
